name: Trigger auto deployment for kedsouza-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/kedsouza-ca-AutoDeployTrigger-1163b4b5-d2e0-47f9-8a78-51201a2d134f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KEDSOUZACA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: kedsouzaacr.azurecr.io
          registryUsername: ${{ secrets.KEDSOUZACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KEDSOUZACA_REGISTRY_PASSWORD }}
          containerAppName: kedsouza-ca
          resourceGroup: kedsouza-ca
          imageToBuild: kedsouzaacr.azurecr.io/kedsouza-ca:${{ github.sha }}
          

     

